# Generated by Django 4.0.4 on 2022-10-31 07:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='contentfiles')),
            ],
        ),
        migrations.CreateModel(
            name='Estelam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuedat', models.DateTimeField(default=datetime.datetime(2022, 10, 31, 7, 14, 7, 252729))),
                ('description', models.TextField(blank=True, null=True)),
                ('trackingnumber', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('familyname', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.TextField(blank=True, null=True)),
                ('job', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(default=0)),
                ('datejoin', models.DateTimeField(default=datetime.datetime(2022, 10, 31, 7, 14, 7, 251571))),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('staffcode', models.IntegerField(default=0)),
                ('password', models.TextField(blank=True, max_length=10, null=True)),
                ('section', models.TextField(blank=True, null=True)),
                ('load', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.mainuser')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('issuedat', models.DateTimeField(default=datetime.datetime(2022, 10, 31, 7, 14, 7, 253683))),
                ('file', models.FileField(blank=True, null=True, upload_to='statusfiles')),
                ('estelam', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.estelam')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.staff')),
            ],
        ),
        migrations.CreateModel(
            name='EstelamFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='estelamfiles')),
                ('estelam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estelam')),
            ],
        ),
        migrations.AddField(
            model_name='estelam',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.staff'),
        ),
        migrations.AddField(
            model_name='estelam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.mainuser'),
        ),
    ]
