# Generated by Django 4.0.4 on 2022-11-01 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sms_remove_mainuser_familyname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estelam',
            name='issuedat',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 8, 48, 12, 79777)),
        ),
        migrations.AlterField(
            model_name='estelam',
            name='trackingnumber',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='datejoin',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 8, 48, 12, 78621)),
        ),
        migrations.AlterField(
            model_name='sms',
            name='issued',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 8, 48, 12, 81320)),
        ),
        migrations.AlterField(
            model_name='status',
            name='issuedat',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 8, 48, 12, 80654)),
        ),
    ]
